---
Admin:
  retry_interval: 300

# List of Flow Collectors
fcs:
- fc_ip: x.x.x.x
  fc_username: <username>
  fc_password: <password>
- fc_ip: y.y.y.y
  fc_username: <username>
  fc_password: <password>
